spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}
      file-size-threshold: ${FILE-SIZE-THRESHOLD:2KB}
  profiles:
    group:
      default-group: base, default
      dev-group: base, dev
      prod-group: base, prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fnb}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:P@ssword789}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:P@ssword789}
      database: ${REDIS_DATABASE:0}
  minio:
    url: ${MINIO_URL:http://127.0.0.1:9000}
    bucket: ${MINIO_BUCKET:ecommerce}
    access-key: ${MINIO_ACCESS_KEY:Q3AM3UQ867SPQQA43P2F}
    secret-key: ${MINIO_SECRET_KEY:tfteSlswRu7BJ86wekitnifILbZam1KYY3TG}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.tiktzuki.com/realms/ecommerce}
  jpa:
    hibernate:
      ddl-auto: update
keycloak:
  auth-server-url: ${KEYCLOAK_HOST:https://keycloak.tiktzuki.com}
  realm: ${KEYCLOAK_REALM:fnb-cms}
  resource: ${KEYCLOAK_RESOURCE:realm-management}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:WE6ybGtJIrOR2jn9tucxsvZfxrZnl2D7}
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: full
      sms:
        url: ${SMS_URL:https://sms.sunshineapp.vn/api}
        token: ${SMS_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImFkbWluIiwiaWF0IjoxNTE2MjM5MDIyfQ.wuHYbExf8mo06-RveSfS2GZt6MOR1_ahgU7T58HFdxQ}